### ISSUE TITLE
Deployments are failing in the production environment

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulbot#121]
While attempting to simply update this with `sprintfjs`, I have found that there is also another error now:

```
[Fri Oct 21 2022 14:26:51 GMT+0000 (Coordinated Universal Time)] ERROR TypeError: Cannot read property 'name' of undefined
    at TextListener.callback (/opt/pulbot/shared/node_modules/hubot-deploy/src/scripts/deploy.coffee:137:106)
    at /opt/pulbot/shared/node_modules/hubot/src/listener.coffee:65:12
    at allDone (/opt/pulbot/shared/node_modules/hubot/src/middleware.coffee:44:37)
    at /opt/pulbot/shared/node_modules/hubot/node_modules/async/lib/async.js:274:13
    at /opt/pulbot/shared/node_modules/hubot/node_modules/async/lib/async.js:154:25
    at /opt/pulbot/shared/node_modules/hubot/node_modules/async/lib/async.js:271:17
    at nextFunc (/opt/pulbot/shared/node_modules/hubot/src/middleware.coffee:33:35)
    at /opt/pulbot/releases/20221021142436/scripts/listener_middleware.coffee:44:9
    at /opt/pulbot/shared/node_modules/hubot/src/middleware.coffee:36:24
    at /opt/pulbot/shared/node_modules/hubot/node_modules/async/lib/async.js:269:13
    at iterate (/opt/pulbot/shared/node_modules/hubot/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/opt/pulbot/shared/node_modules/hubot/node_modules/async/lib/async.js:162:9)
    at Object.async.reduce (/opt/pulbot/shared/node_modules/hubot/node_modules/async/lib/async.js:268:15)
    at /opt/pulbot/shared/node_modules/hubot/src/middleware.coffee:49:13
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by jrgriffiniii** [comment]
The offending line is here:

```coffee
    if robot.adapterName is "slack"
      deployment.user = user.name
      # .name here is null
      deployment.room = robot.adapter.client.rtm.dataStore.getChannelGroupOrDMById(msg.message.user.room).name
```

**Comment by jrgriffiniii** [comment]
Somehow the `rtm.dataStore` does not resolve to the Slack room name. I am looking for a proper solution for this:

```
135     if robot.adapterName is "slack"
136       deployment.user = user.name
137       robot.logger.info "debug: #{msg.message.user.room}"
138       #deployment.room = robot.adapter.client.rtm.dataStore.getChannelGroupOrDMById(msg.message.user.room).name
139       deployment.room = "robots"
```

**Comment by jrgriffiniii** [comment]
The Channel ID passed is the following:

```
[Fri Oct 21 2022 14:45:23 GMT+0000 (Coordinated Universal Time)] INFO debug: G9Z5GB5AL
```

...yet the functionality implemented is the following:

```javascript
SlackDataStore.prototype.getChannelGroupOrDMById = function getChannelGroupOrDMById(objId) {
   var ret;
   var firstChar = objId.substring(0, 1);

   if (firstChar === 'C') {
     ret = this.getChannelById(objId);
   } else if (firstChar === 'G') {
     ret = this.getGroupById(objId);
   } else if (firstChar === 'D') {
     ret = this.getDMById(objId);
   }
```

This should be a code beginning with `C`.

**Comment by jrgriffiniii** [comment]
Oddly enough, with `figgy` deployments, the code passed is a different code:

```
[Fri Oct 21 2022 14:49:13 GMT+0000 (Coordinated Universal Time)] INFO debug: CA8282VKN
```
